### ISSUE TITLE
ReferenceError: 'google' is not defined

### ISSUE THREAD

**Issue by jasyyang** [camtheman256/6.1040-final-project#27]
https://github.com/camtheman256/6.1040-final-project/blob/12af706127b38bcc54367e44c195e00af64389cf/backend/space/model.ts#L62

**Comment by jasyyang** [comment]
<img width="1155" alt="Screen Shot 2022-12-04 at 3 06 23 PM" src="https://user-images.githubusercontent.com/43073399/205512945-64bbe62c-0191-429b-9295-185dec8e85e5.png">

**Comment by camtheman256** [comment]
Ok the culprit is this line. This line is actually _not_ in TypeScript, whereas google.maps.LatLng is something only defined in TypeScript. This line is a mongoose type definition, which only supports these specific types, not any TypeScript type: https://mongoosejs.com/docs/api/schema.html#schema_Schema-Types
